Squeal_UI/Models/TivitIndexViewModel.cs
using Squeal_EL.IdentityModels;
using Squeal_EL.ViewModels;
using System.ComponentModel.DataAnnotations;

namespace Squeal_UI.Models
{
    public class TivitIndexViewModel
    {
        public long Id { get; set; }

        public DateTime InsertedDate { get; set; }

        [StringLength(500)]
        [MinLength(2)]
        public string Tivit { get; set; }

        public string UserId { get; set; }

        public bool IsDefaultTivit { get; set; } // ekstra

        public bool IsDeleted { get; set; }

        public AppUser? AppUser { get; set; }

        public List<IFormFile>? TivitPictures { get; set; }

        public List<TivitMediaDTO>? TivitPhotos { get; set; }

    }
}

Squeal_UI/Components/YanMenuViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Squeal_BL.InterfacesOfManagers;
using Squeal_EL.IdentityModels;
using Squeal_EL.ResultModels;
using Squeal_EL.ViewModels;
using Squeal_UI.Models;

namespace Squeal_UI.Components
{
    public class YanMenuViewComponent : ViewComponent
    {
        private readonly ITivitTagManager _tagManager;
        private readonly IMapper _mapper;

        public YanMenuViewComponent(ITivitTagManager tagManager, IMapper mapper)
        {
            _tagManager = tagManager;
            _mapper = mapper;
        }

        public IViewComponentResult Invoke()
        {
            try
            {
                var taglar = _tagManager.GetAll(x => !x.IsDeleted).Data.GroupBy(x => x.TagName).Select(group => group.First()).ToList();
                var model = _mapper.Map<List<TivitTagDTO>>(taglar);

                return View(model);
            }
            catch (Exception ex)
            {
                return View();
            }
        }
    }
}

Squeal_UI/Controllers/HomeController.cs
using AutoMapper;
using DocumentFormat.OpenXml.Office.CustomUI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NuGet.Packaging;
using Squeal_BL.ImplementationOfManagers;
using Squeal_BL.InterfacesOfManagers;
using Squeal_EL.IdentityModels;
using Squeal_EL.ResultModels;
using Squeal_EL.ViewModels;
using Squeal_UI.Models;
using System.Diagnostics;
using System.Linq;

namespace Squeal_UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<AppUser> _userManager;
        private readonly IUserTivitManager _userTivitManager;
        private readonly ITivitMediaManager _mediaManager;
        private readonly ITivitTagManager _tagManager;
        private readonly IMapper _mapper;

        public HomeController(ILogger<HomeController> logger, UserManager<AppUser> userManager, IUserTivitManager userTivitManager, ITivitMediaManager mediaManager, ITivitTagManager tagManager, IMapper mapper)
        {
            _logger = logger;
            _userManager = userManager;
            _userTivitManager = userTivitManager;
            _mediaManager = mediaManager;
            _tagManager = tagManager;
            _mapper = mapper;
        }

        

        public IActionResult Index(string Tagname)
        {
            var tag = _tagManager.GetAll(x => x.TagName == Tagname).Data.ToList();

            List<long> dizi = new List<long>();

            foreach (var itm in tag)
            {
                dizi.Add(itm.TivitId);
            }

            var tivits = _userTivitManager.GetAll(x => !x.IsDeleted).Data.OrderByDescending(x => x.InsertedDate).ToList();


            if (Tagname != null)
            {
                tivits = _userTivitManager.GetAll(x => !x.IsDeleted && dizi.Contains(x.Id)).Data.OrderByDescending(x => x.InsertedDate).ToList();
            }


            var model = _mapper.Map<List<TivitIndexViewModel>>(tivits);

            foreach (var tivit in model)
            {
                var media = _mediaManager.GetAll(x => x.TivitId == tivit.Id).Data;
                if (media.Count == 0)
                {
                    tivit.TivitPhotos = null;
                }
                else
                {
                    tivit.TivitPhotos = new List<TivitMediaDTO>();
                    foreach (var item in media)
                    {
                        tivit.TivitPhotos.Add(item);
                    }
                }
            }

            return View(model);
        }


            public IActionResult Privacy()
        {
            return View();
        }
        [Authorize]
        public IActionResult TivitIndex()
        {
            //useridyi sayfaya gönderelim böylece adres eklemede useridyi metoda aktarabiliriz
            var username = User.Identity?.Name;
            var user = _userManager.FindByNameAsync(username).Result;
            TivitIndexViewModel model = new TivitIndexViewModel();
            model.TivitPictures = new List<IFormFile>();
            model.UserId = user.Id;
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public IActionResult TivitIndex(TivitIndexViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    _logger.LogError($"HATA: Home/TivitIndex post model:{JsonConvert.SerializeObject(model)}");
                    ModelState.AddModelError("", "Lütfen bilgileri eksiksiz giriniz!");
                    return View(model);
                }

                var tivit = _mapper.Map<UserTivitDTO>(model);
                tivit.InsertedDate = DateTime.Now;

                var result2 = _userTivitManager.Add(tivit);
                if (!result2.IsSuccess)
                {
                    _logger.LogError($"HATA: Home/TivitIndex post model:{JsonConvert.SerializeObject(model)}");
                    ModelState.AddModelError("", "Tivit kaydedilemedi!");
                    return View(model);
                }

                //tivitteki tag arama algoritması

                var tivittext = tivit.Tivit;
                string[] words = tivittext.Split(' '); // Metni boşluklara göre ayır
                List<string> Taglar = new List<string>();

                bool tageklendimi = false;

                foreach (string word in words)
                {
                    if (word.StartsWith("#"))
                    {
                        TivitTagDTO tt = new TivitTagDTO()
                        {
                            InsertedDate = DateTime.Now,
                            TagName = word.Substring(1),
                            IsDeleted = false,
                            TivitId = result2.Data.Id
                        };
                        var result4 = _tagManager.Add(tt);
                        if (result4.IsSuccess) { tageklendimi = true; }
                    }
                }

                if (model.TivitPictures != null)
                {
                    foreach (var item in model.TivitPictures)
                    {
                        if (item.ContentType.Contains("image") && item.Length > 0)
                        {
                            string fileName = $"{item.FileName.Substring(0, item.FileName.IndexOf('.'))}-{Guid.NewGuid().ToString().Replace("-", "")}";

                            string uzanti = Path.GetExtension(item.FileName);

                            string path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot/TivitPictures/{fileName}{uzanti}");

                            string directoryPath =
                               Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot/TivitPictures/");

                            if (!Directory.Exists(directoryPath))
                                Directory.CreateDirectory(directoryPath);

                            using var stream = new FileStream(path, FileMode.Create);

                            item.CopyTo(stream);
                            TivitMediaDTO p = new TivitMediaDTO()
                            {
                                InsertedDate = DateTime.Now,
                                MediaPath = $"/TivitPictures/{fileName}{uzanti}",
                                TivitId = result2.Data.Id
                            };

                            var result1 = _mediaManager.Add(p);
                            if (!result1.IsSuccess)
                            {
                                _logger.LogError($"HATA: Home/TivitIndex post model:{JsonConvert.SerializeObject(model)}");
                                ModelState.AddModelError("", "Tivit kaydedilemedi!");
                                return View(model);
                            }
                        }
                    }
                }

                TempData["TivitIndexSuccessMsg"] = "Tivit attınız!" + (tageklendimi ? " Tag eklendi" : "");

                _logger.LogInformation($"Home/TivitIndex atılan tivit: {JsonConvert.SerializeObject(model)}");
                return RedirectToAction("TivitIndex", "Home");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"HATA: Home/TivitIndex post model:{JsonConvert.SerializeObject(model)}");
                ModelState.AddModelError("", "Beklenmedik bir sorun oluştu!");
                return View(model);
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Squeal_UI/Views/Home/Index.cshtml
@model List<TivitIndexViewModel>
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_tema24.cshtml";
}

@* Yeni tema ile *@

<div class="container-fluid pb-4 pt-4 paddding">
    <div class="container paddding">
        <div class="row mx-0">
            <div class="col-md-8 animate-box" data-animate-effect="fadeInLeft">
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Sayfan</div>
                </div>
                @foreach (var item in Model)
                {
                    <div class="row pb-10" style=" margin-bottom:70px">
                        <div class="col-md-9">
                            <div class="fh5co_hover_news_img">
                                <div style="display: flex; align-items: center; margin:10px">
                                    <div style="width: 75px; height: 75px; overflow: hidden; border-radius: 50%;">
                                        @{
                                            if(item.AppUser.ProfilePicture!=null)
                                            {
                                                <img src="@item.AppUser.ProfilePicture" style="width: 100%; height: 100%; object-fit: cover;" />
                                            }
                                            else
                                            {
                                                   <img src="/profilepicture.jpg" style="width: 100%; height: 100%; object-fit: cover;"/>
                                            }
                                        }
                                    </div>
                                    <div style="margin-left: 10px;">
                                        <a><b>@item.AppUser.Name @item.AppUser.Surname</b></a>
                                        <a>@Html.Raw("@")<span style="font-style: italic;">@item.AppUser.UserName - @item.InsertedDate</span></a>

                                        <div class="fh5co_consectetur">
                                            @item.Tivit
                                        </div>

                                    </div>
                                </div>

                                @{
                                    if (item.TivitPhotos != null)
                                    {
                                        @foreach (var media in item.TivitPhotos)
                                        {
                                            <div>
                                                <img src="@media.MediaPath" alt="" style="max-width: 480px; max-height: 320px;" />
                                            </div>

                                        }
                                    }
                                }
                            </div>
                        </div>
                    </div>
                }


            </div>

            @await Component.InvokeAsync("YanMenu")

        </div>
    </div>
    @* <div class="row mx-0">
        <div class="col-12 text-center pb-4 pt-4">
            <a href="#" class="btn_mange_pagging"><i class="fa fa-long-arrow-left"></i>&nbsp;&nbsp; Previous</a>
            <a href="#" class="btn_pagging">1</a>
            <a href="#" class="btn_pagging">2</a>
            <a href="#" class="btn_pagging">3</a>
            <a href="#" class="btn_pagging">...</a>
            <a href="#" class="btn_mange_pagging">Next <i class="fa fa-long-arrow-right"></i>&nbsp;&nbsp; </a>
        </div>
    </div> *@
</div>

Squeal_UI/Views/Home/TivitIndex.cshtml
@model TivitIndexViewModel
@{
    ViewData["Title"] = "TivitIndex";
    Layout = "~/Views/Shared/_tema24.cshtml";
}

@if (TempData["TivitIndexSuccessMsg"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>BİLGİ!</strong> @TempData["TivitIndexSuccessMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <br />
}

<div class="row justify-content-center" style="margin-top: 20px;">
    <form asp-controller="Home" asp-action="TivitIndex" method="post"
          enctype="multipart/form-data">
        <input type="hidden" asp-for="UserId" />
        <div class="col-12">
            <div class="col-9">
                <textarea class="form-control" asp-for="Tivit" id="tivitmessage"></textarea>
                <p id="sayim">0/500</p>
                <span style="float:right"
                      class="badge bg-secondary" id="tivitmessagebadge"></span>
                <input type="file" asp-for="TivitPictures" multiple accept=".png, .jpg, .jpeg" />
            </div>
            <div class="col-3">
                <button type="submit" class="btn btn-info">Gönder</button>
            </div>
        </div>
    </form>
</div>

<div class="tivitdiv">
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $("#tivitmessage").keyup(function () {
                var characterCount = $("#tivitmessage").val().length;
                var x = characterCount + "/500";

                document.getElementById("sayim").innerHTML = x
                $("#tivitmessagebadge").text(x);
                console.log(x);
            });
        });
    </script>
}